package com.learning.urlshortener.service;

import com.learning.urlshortener.dto.CreateUrlRequest;
import com.learning.urlshortener.dto.UpdateUrlRequest;
import com.learning.urlshortener.dto.UrlResponse;
import com.learning.urlshortener.entity.UrlMapping;
import com.learning.urlshortener.exception.DuplicateResourceException;
import com.learning.urlshortener.exception.ResourceNotFoundException;
import com.learning.urlshortener.repository.UrlMappingRepository;
import com.learning.urlshortener.util.Base62Encoder;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class UrlService {

    private static final String BASE_SHORT_URL = "http://localhost:8080/r/";

    private final UrlMappingRepository urlMappingRepository;

    public UrlResponse createShortUrl(CreateUrlRequest request) {

        boolean userWantsCustomAlias =
                request.getCustomAlias() != null && !request.getCustomAlias().isBlank();

        UrlMapping savedUrl;

        if (userWantsCustomAlias) {
            savedUrl = createWithCustomAlias(request);
        } else {
            savedUrl = createWithAutoGeneratedCode(request);
        }

        return toResponse(savedUrl);
    }

    private UrlMapping createWithCustomAlias(CreateUrlRequest request) {
        String alias = request.getCustomAlias();

        boolean aliasAlreadyTaken = urlMappingRepository.existsByShortCode(alias);
        if (aliasAlreadyTaken) {
            throw new DuplicateResourceException("This custom alias is already taken: " + alias);
        }

        UrlMapping urlMapping = buildNewUrlMapping(request);
        urlMapping.setShortCode(alias);

        return urlMappingRepository.save(urlMapping);
    }

    private UrlMapping createWithAutoGeneratedCode(CreateUrlRequest request) {
        UrlMapping urlMapping = buildNewUrlMapping(request);

        // Step 1: save with a placeholder, just to get a real database ID.
        urlMapping.setShortCode("TEMP");
        UrlMapping savedUrl = urlMappingRepository.save(urlMapping);

        // Step 2: now that we have a real ID (e.g. 47), turn it into a short code.
        Long newlyAssignedId = savedUrl.getId();
        String generatedShortCode = Base62Encoder.encode(newlyAssignedId);

        // Step 3: save again with the correct short code.
        savedUrl.setShortCode(generatedShortCode);
        return urlMappingRepository.save(savedUrl);
    }

    private UrlMapping buildNewUrlMapping(CreateUrlRequest request) {
        UrlMapping urlMapping = new UrlMapping();
        urlMapping.setOriginalUrl(request.getOriginalUrl());
        urlMapping.setExpirationDate(request.getExpirationDate());
        return urlMapping;
    }


    public UrlMapping getByShortCodeAndIncrementClicks(String shortCode) {
        UrlMapping urlMapping = urlMappingRepository.findByShortCode(shortCode)
                .orElseThrow(() -> new ResourceNotFoundException("Short URL not found: " + shortCode));

        if (urlMapping.isExpired()) {
            throw new ResourceNotFoundException("This short URL has expired: " + shortCode);
        }

        long newClickCount = urlMapping.getClickCount() + 1;
        urlMapping.setClickCount(newClickCount);
        urlMappingRepository.save(urlMapping);

        return urlMapping;
    }

    public Page<UrlResponse> listUrls(String search, Pageable pageable) {
        boolean noSearchTermGiven = (search == null || search.isBlank());

        Page<UrlMapping> page;
        if (noSearchTermGiven) {
            page = urlMappingRepository.findAll(pageable);
        } else {
            page = urlMappingRepository.findByOriginalUrlContainingIgnoreCase(search, pageable);
        }

        return page.map(this::toResponse);
    }


    public UrlResponse updateUrl(Long id, UpdateUrlRequest request) {
        UrlMapping urlMapping = findUrlByIdOrThrow(id);
        urlMapping.setOriginalUrl(request.getOriginalUrl());
        urlMappingRepository.save(urlMapping);
        return toResponse(urlMapping);
    }


    public void deleteUrl(Long id) {
        UrlMapping urlMapping = findUrlByIdOrThrow(id);
        urlMappingRepository.delete(urlMapping);
    }

    private UrlMapping findUrlByIdOrThrow(Long id) {
        return urlMappingRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("URL not found with id: " + id));
    }

    private UrlResponse toResponse(UrlMapping urlMapping) {
        String fullShortUrl = BASE_SHORT_URL + urlMapping.getShortCode();

        return new UrlResponse(
                urlMapping.getId(),
                urlMapping.getOriginalUrl(),
                urlMapping.getShortCode(),
                fullShortUrl,
                urlMapping.getExpirationDate(),
                urlMapping.getClickCount(),
                urlMapping.getCreatedAt()
        );
    }
}